var predefinedWords = [
    "1", "17", "18", "19", "2", "3", "4", "5", "6", "I",
    "SUV", "a", "ac", "accountant", "actor", "actress", "alligator", "amount", "animals", "apple", "around",
    "aunt", "author", "avocado", "b", "baby", "bad", "basement", "bath", "bathroom", "bathtub",
    "bed comforter", "bedroom", "bee", "bell", "big", "bill", "biologist", "bird", "black", "blanket",
    "blinds", "blue", "boy", "bread", "breakfast", "broom", "brother", "brown", "brush teeth", "bug",
    "bus", "butter", "c", "cake", "calendar", "camera", "candle", "candy", "captions", "car",
    "cashier", "cat", "ceiling fan", "cent", "cereal", "cheese", "chemist", "church", "circle", "clarinet",
    "clock", "closet", "clothes", "coffee machine", "coffee table", "coins change", "cold", "color", "come", "cookie",
    "cool", "cop", "corner", "cost", "couch", "counselor", "counter", "cousin", "cow", "cry",
    "cup", "curtain", "d", "dad", "date", "daughter", "day", "dentist", "designer", "dictionary",
    "dinner", "dishwasher", "divorce", "doctor", "dog", "dollar", "donkey", "don't believe", "don't care", "don't know",
    "don't like", "don't look at me", "don't mind", "don't understand", "don't want", "door", "dresser", "drink", "drums", "e",
    "eat", "economist", "egg", "elevator", "engineer", "entrepreneur", "envelope", "eraser", "excuse", "f",
    "family", "feelings", "file folder", "fine", "finish", "fisherman", "floor level", "florist", "flute", "folding chair",
    "food", "fork", "freezer", "friday", "fridge", "friend", "frog", "full", "furniture", "future will",
    "g", "game", "garage", "get in", "get out", "girl", "glue", "gold", "good", "grandma",
    "grandpa", "grapes", "green", "guitar", "h", "hamburger", "hammer", "happy", "harmonica", "harp",
    "have", "headache", "health", "help", "highway", "freeway", "home", "horse", "hot", "hotdog", "house",
    "how are you", "how", "hungry", "hurt", "husband", "i", "icecream", "in", "instrument", "interpreter",
    "intersection", "j", "janitor", "k", "key", "kitchen", "knife", "l", "lamp", "laundry room",
    "lawyer", "left side right side", "left side", "left", "letter", "like", "lion", "love", "lunch", "m",
    "mad", "magazine", "man", "manager", "marriage", "match", "me", "mechanic", "medicine", "metal",
    "microwave", "milk", "mirror", "mom", "monday", "money", "month", "more", "morning", "mouse",
    "music", "must", "myself", "n", "nail clipper", "name", "need", "newspaper", "nice clean", "night",
    "no", "noon", "now", "current", "nurse", "o", "orange", "organ", "our", "out",
    "p", "past", "before", "peach", "penny", "pharmacist", "phone book", "phone", "photo album", "photographer",
    "physical therapist", "physicist", "piano", "picture", "pig", "pillow", "pilot", "pin", "pink", "places",
    "plant", "play", "player", "please", "polish", "programmer", "psychologist", "purple", "q", "r",
    "rain", "really fine", "rectangle", "red", "request", "rhombus", "ride in", "ride on", "right side", "right",
    "rocking chair", "rug", "s", "sad", "sales person", "saturday", "school", "scientist", "scissors", "screwdriver",
    "sewing thread", "sheep", "shelves", "shirt", "shoes", "short", "shower", "sign", "silver", "sister",
    "skill", "sleep", "sleeping bag", "small", "snake", "snow", "soap", "socks", "soldier", "son",
    "sorry", "spoon", "square", "stairs", "stamp", "stapler", "stop light", "stop sight", "stop", "store",
    "stove", "summer", "sunday", "t", "table", "tall", "tape", "teacher", "team", "technician",
    "thank you", "that", "thursday", "tiger", "tissue", "paper", "toaster", "today", "touch", "towel",
    "town", "traffic", "train", "trainer", "transfer", "triangle", "trombone", "trumpet", "try", "tuesday",
    "turtle", "tv", "two floors", "u", "umbrella", "uncle", "understand", "v", "vacuum", "van",
    "videophone", "videotape", "violin", "volunteer", "w", "waiter", "want", "warm", "warning", "wash",
    "water", "wednesday", "week", "weekdays", "weekend", "what", "when", "where", "white", "who",
    "why", "wife", "window", "with", "woman", "work", "wrong", "x", "y", "year",
    "yellow", "yes", "you", "your", "z"
];